FROM java


COPY /project/microservice-discovery-eureka/target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar  /usr/src/myapp/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
